name: RDP Free Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo systemctl enable --now tailscaled

      - name: Connect to Tailscale
        run: |
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname github-rdp --accept-routes

      - name: Setup RDP user
        run: |
          sudo apt update
          sudo apt install -y xrdp xfce4 xfce4-goodies
          sudo adduser rdpuser --gecos "" --disabled-password
          echo 'rdpuser:rdppassword' | sudo chpasswd
          sudo adduser rdpuser sudo
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          echo "RDP username: rdpuser"
          echo "RDP password: rdppassword"

      - name: Show connection info
        run: |
          tailscale ip -4
          echo "Gunakan IP di atas untuk konek via RDP: mstsc (Windows) / Remmina (Linux) / Microsoft Remote Desktop (Android)."
          echo "User: rdpuser | Password: rdppassword"

      - name: Keep alive
        run: sleep 6h
