name: desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Set up job
      run: echo "Starting Tailscale RDP session..."

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup display and install packages
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          xfce4 xfce4-terminal dbus-x11 x11vnc xvfb \
          tigervnc-standalone-server wget unzip python3-pip tailscale

    - name: Configure VNC password
      run: |
        mkdir -p ~/.vnc
        echo "$VNC_PASSWORD" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd

    - name: Start Xvfb and XFCE
      run: |
        export DISPLAY=:0
        Xvfb :0 -screen 0 1280x720x16 &
        sleep 3
        startxfce4 &

    - name: Start x11vnc (serve VNC on :5901)
      run: |
        x11vnc -display :0 -rfbauth ~/.vnc/passwd -forever -shared -rfbport 5901 &

    - name: Install and start Tailscale
      run: |
        sudo tailscaled &
        sleep 5
        sudo tailscale up --authkey $TAILSCALE_AUTHKEY --hostname github-rdp --accept-routes

    - name: Show connection info
      run: |
        echo "Your Tailscale node is ready!"
        tailscale ip -4
        echo "Use any VNC viewer to connect to 127.0.0.1:5901 via Tailscale"

    - name: Keep job alive (tail logs)
      run: |
        echo "RDP session active. Press Ctrl+C to stop."
        sleep 9999999
