name: desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Set up job
      run: echo "🚀 Starting Tailscale + XFCE Desktop session..."

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup display and install packages
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          xfce4 xfce4-terminal dbus-x11 x11vnc xvfb \
          tigervnc-standalone-server wget unzip python3-pip curl gnupg lsb-release

        # Tambahkan repo resmi Tailscale
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/$(lsb_release -cs).noarmor.gpg | \
          sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg > /dev/null

        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/$(lsb_release -cs).tailscale-keyring.list | \
          sudo tee /etc/apt/sources.list.d/tailscale.list > /dev/null

        sudo apt-get update
        sudo apt-get install -y tailscale

    - name: Configure VNC password
      env:
        VNC_PASSWORD: "123456"
      run: |
        mkdir -p ~/.vnc
        echo "$VNC_PASSWORD" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd

    - name: Start Xvfb and XFCE
      run: |
        export DISPLAY=:0
        Xvfb :0 -screen 0 1280x720x16 &
        sleep 3
        startxfce4 &

    - name: Start x11vnc (serve VNC on :5901)
      run: |
        x11vnc -display :0 -rfbauth ~/.vnc/passwd -forever -shared -rfbport 5901 &

    - name: Install and start Tailscale
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      run: |
        sudo tailscaled &
        sleep 8
        sudo tailscale up --authkey=${TAILSCALE_AUTHKEY} --hostname=github-rdp --accept-routes --ssh

    - name: Show connection info
      run: |
        echo "✅ Tailscale node ready!"
        tailscale ip -4
        echo ""
        echo "🖥️ Connect using any VNC client:"
        echo "VNC IP: (lihat IP di atas)"
        echo "Port : 5901"
        echo "Password : 123456"

    - name: Keep job alive
      run: sleep 9999999
