name: Remote Desktop via noVNC + Tailscale

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup display and install packages
        run: |
          sudo apt-get update -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 xfce4-terminal dbus-x11 x11vnc xvfb wget unzip python3-pip
          sudo pip3 install websockify
          # install noVNC
          wget -q https://github.com/novnc/noVNC/archive/refs/heads/master.zip -O novnc.zip
          unzip -q novnc.zip
          mv noVNC-master novnc
          mkdir -p /home/runner/.vnc

      - name: Configure VNC password
        env:
          VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        run: |
          echo "$VNC_PASSWORD" | vncpasswd -f > /home/runner/.vnc/passwd
          chmod 600 /home/runner/.vnc/passwd

      - name: Start Xvfb and XFCE
        run: |
          export DISPLAY=:1
          Xvfb :1 -screen 0 1280x720x24 & sleep 1
          export DBUS_SESSION_BUS_ADDRESS=/tmp/dbus-1
          dbus-launch --exit-with-session xfce4-session &
          sleep 4

      - name: Start x11vnc (serve VNC on :5901)
        run: |
          export DISPLAY=:1
          nohup x11vnc -display :1 -rfbauth /home/runner/.vnc/passwd -forever -shared -rfbport 5901 >/tmp/x11vnc.log 2>&1 &
          sleep 2
          tail -n +1 /tmp/x11vnc.log || true

      - name: Start noVNC (websockify) on port 6080
        run: |
          export DISPLAY=:1
          nohup ./novnc/utils/novnc_proxy --vnc localhost:5901 --listen 6080 >/tmp/novnc.log 2>&1 &
          sleep 2
          tail -n +1 /tmp/novnc.log || true

      - name: Install Tailscale
        run: |
          # Install tailscale
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.gpg | sudo gpg --dearmor -o /usr/share/keyrings/tailscale-archive-keyring.gpg
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.list | sudo tee /etc/apt/sources.list.d/tailscale.list
          sudo apt-get update -y
          sudo apt-get install -y tailscale

      - name: Start tailscaled and join Tailnet
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          sudo tailscaled --state=/tmp/tailscaled.state --socket=/tmp/tailscale.sock >/tmp/tailscaled.log 2>&1 &
          sleep 2
          # Bring interface up with authkey (ephemeral / single-use recommended)
          sudo tailscale --socket=/tmp/tailscale.sock up --authkey="${TAILSCALE_AUTHKEY}" --hostname="gh-actions-remote" || (cat /tmp/tailscaled.log && exit 1)
          sleep 3
          # show status
          sudo tailscale --socket=/tmp/tailscale.sock status || true
          sudo tailscale --socket=/tmp/tailscale.sock ip -4 || true

      - name: Show connection info
        run: |
          echo "noVNC should be available on port 6080 of the runner's Tailscale IP."
          echo "Runner Tailscale IPv4(s):"
          sudo tailscale --socket=/tmp/tailscale.sock ip -4

      - name: Keep job alive (tail logs)
        run: |
          echo "Job is running. Open http://<TAILSCALE_IP>:6080 from a device in the same Tailnet."
          tail -f /tmp/novnc.log /tmp/x11vnc.log /tmp/tailscaled.log
